### ISSUE TITLE
37期到42期摆放顺序反了

### ISSUE THREAD

**Issue by yinbun** [JayHeng/pzh-mcu-bi-weekly#1]
# 痞子衡嵌入式半月刊： 第 x 期

![](http://henjay724.com/image/cnblogs/pzh_mcu_bi_weekly.PNG)

这里分享嵌入式领域有用有趣的项目/工具以及一些热点新闻，农历年分二十四节气，希望在每个交节之日准时发布一期。

本期刊是开源项目（GitHub: [JayHeng/pzh-mcu-bi-weekly](https://github.com/JayHeng/pzh-mcu-bi-weekly)），欢迎提交 issue，投稿或推荐你知道的嵌入式那些事儿。

## 唠两句

本期共收录 x条资讯、x个项目、x个工具，希望对你有帮助！

### <font color="red">1、</font>

![]()

**Comment by JayHeng** [comment]
细心
